packages:
  - apps/*
  - packages/*

allowBuilds:
  "@parcel/watcher": true

verifyDepsBeforeRun: false

nodeLinker: hoisted
supportedArchitectures:
  os:
    - win32
    - current
  cpu:
    - x64
    - current
